apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: dmb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: alimx07/post_service
