apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: dmb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: alimx07/post_service:e47434c0ec47e2e8d10ecf17f22a6847e969cace
