apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: dmb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: alimx07/post_service:b3e7068d99dc40c223cd4d3c2b404ac4bca52747
