CREATE TABLE IF NOT EXISTS posts(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	likes_count BIGINT NOT NULL,
	comments_count BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INT NOT NULL,
	post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS likes(
	post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT NoW(),
	PRIMARY KEY (post_id , user_id)
);