// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: follow.proto

package services_bindings_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsCelebReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCelebReq) Reset() {
	*x = IsCelebReq{}
	mi := &file_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCelebReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCelebReq) ProtoMessage() {}

func (x *IsCelebReq) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCelebReq.ProtoReflect.Descriptor instead.
func (*IsCelebReq) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{0}
}

func (x *IsCelebReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsCelebRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCeleb       bool                   `protobuf:"varint,1,opt,name=IsCeleb,proto3" json:"IsCeleb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCelebRes) Reset() {
	*x = IsCelebRes{}
	mi := &file_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCelebRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCelebRes) ProtoMessage() {}

func (x *IsCelebRes) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCelebRes.ProtoReflect.Descriptor instead.
func (*IsCelebRes) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{1}
}

func (x *IsCelebRes) GetIsCeleb() bool {
	if x != nil {
		return x.IsCeleb
	}
	return false
}

type GetFollowersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersReq) Reset() {
	*x = GetFollowersReq{}
	mi := &file_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersReq) ProtoMessage() {}

func (x *GetFollowersReq) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersReq.ProtoReflect.Descriptor instead.
func (*GetFollowersReq) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerID    []string               `protobuf:"bytes,1,rep,name=FollowerID,proto3" json:"FollowerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRes) Reset() {
	*x = GetFollowersRes{}
	mi := &file_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRes) ProtoMessage() {}

func (x *GetFollowersRes) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRes.ProtoReflect.Descriptor instead.
func (*GetFollowersRes) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowersRes) GetFollowerID() []string {
	if x != nil {
		return x.FollowerID
	}
	return nil
}

type CreateFollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`         // The user who is following (follower) - extracted from JWT
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=FolloweeId,proto3" json:"FolloweeId,omitempty"` // The user to be followed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFollowReq) Reset() {
	*x = CreateFollowReq{}
	mi := &file_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFollowReq) ProtoMessage() {}

func (x *CreateFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFollowReq.ProtoReflect.Descriptor instead.
func (*CreateFollowReq) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFollowReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateFollowReq) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type DeleteFollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`         // The user who is unfollowing (follower) - extracted from JWT
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=FolloweeId,proto3" json:"FolloweeId,omitempty"` // The user to be unfollowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFollowReq) Reset() {
	*x = DeleteFollowReq{}
	mi := &file_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFollowReq) ProtoMessage() {}

func (x *DeleteFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFollowReq.ProtoReflect.Descriptor instead.
func (*DeleteFollowReq) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFollowReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteFollowReq) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{6}
}

func (x *FollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_follow_proto protoreflect.FileDescriptor

const file_follow_proto_rawDesc = "" +
	"\n" +
	"\ffollow.proto\"$\n" +
	"\n" +
	"IsCelebReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"&\n" +
	"\n" +
	"IsCelebRes\x12\x18\n" +
	"\aIsCeleb\x18\x01 \x01(\bR\aIsCeleb\")\n" +
	"\x0fGetFollowersReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"1\n" +
	"\x0fGetFollowersRes\x12\x1e\n" +
	"\n" +
	"FollowerID\x18\x01 \x03(\tR\n" +
	"FollowerID\"I\n" +
	"\x0fCreateFollowReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1e\n" +
	"\n" +
	"FolloweeId\x18\x02 \x01(\tR\n" +
	"FolloweeId\"I\n" +
	"\x0fDeleteFollowReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1e\n" +
	"\n" +
	"FolloweeId\x18\x02 \x01(\tR\n" +
	"FolloweeId\"*\n" +
	"\x0eFollowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xfe\x01\n" +
	"\rFollowService\x122\n" +
	"\fGetFollowers\x12\x10.GetFollowersReq\x1a\x10.GetFollowersRes\x12.\n" +
	"\bGetCeleb\x12\x10.GetFollowersReq\x1a\x10.GetFollowersRes\x12#\n" +
	"\aIsCeleb\x12\v.IsCelebReq\x1a\v.IsCelebRes\x121\n" +
	"\fCreateFollow\x12\x10.CreateFollowReq\x1a\x0f.FollowResponse\x121\n" +
	"\fDeleteFollow\x12\x10.DeleteFollowReq\x1a\x0f.FollowResponseB\x1cZ\x1a../../services_bindings_gob\x06proto3"

var (
	file_follow_proto_rawDescOnce sync.Once
	file_follow_proto_rawDescData []byte
)

func file_follow_proto_rawDescGZIP() []byte {
	file_follow_proto_rawDescOnce.Do(func() {
		file_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)))
	})
	return file_follow_proto_rawDescData
}

var file_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_follow_proto_goTypes = []any{
	(*IsCelebReq)(nil),      // 0: IsCelebReq
	(*IsCelebRes)(nil),      // 1: IsCelebRes
	(*GetFollowersReq)(nil), // 2: GetFollowersReq
	(*GetFollowersRes)(nil), // 3: GetFollowersRes
	(*CreateFollowReq)(nil), // 4: CreateFollowReq
	(*DeleteFollowReq)(nil), // 5: DeleteFollowReq
	(*FollowResponse)(nil),  // 6: FollowResponse
}
var file_follow_proto_depIdxs = []int32{
	2, // 0: FollowService.GetFollowers:input_type -> GetFollowersReq
	2, // 1: FollowService.GetCeleb:input_type -> GetFollowersReq
	0, // 2: FollowService.IsCeleb:input_type -> IsCelebReq
	4, // 3: FollowService.CreateFollow:input_type -> CreateFollowReq
	5, // 4: FollowService.DeleteFollow:input_type -> DeleteFollowReq
	3, // 5: FollowService.GetFollowers:output_type -> GetFollowersRes
	3, // 6: FollowService.GetCeleb:output_type -> GetFollowersRes
	1, // 7: FollowService.IsCeleb:output_type -> IsCelebRes
	6, // 8: FollowService.CreateFollow:output_type -> FollowResponse
	6, // 9: FollowService.DeleteFollow:output_type -> FollowResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_follow_proto_init() }
func file_follow_proto_init() {
	if File_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follow_proto_goTypes,
		DependencyIndexes: file_follow_proto_depIdxs,
		MessageInfos:      file_follow_proto_msgTypes,
	}.Build()
	File_follow_proto = out.File
	file_follow_proto_goTypes = nil
	file_follow_proto_depIdxs = nil
}
