// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: follow.proto

package services_bindings_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsCelebReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCelebReq) Reset() {
	*x = IsCelebReq{}
	mi := &file_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCelebReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCelebReq) ProtoMessage() {}

func (x *IsCelebReq) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCelebReq.ProtoReflect.Descriptor instead.
func (*IsCelebReq) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{0}
}

func (x *IsCelebReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type IsCelebRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCeleb       bool                   `protobuf:"varint,1,opt,name=IsCeleb,proto3" json:"IsCeleb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCelebRes) Reset() {
	*x = IsCelebRes{}
	mi := &file_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCelebRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCelebRes) ProtoMessage() {}

func (x *IsCelebRes) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCelebRes.ProtoReflect.Descriptor instead.
func (*IsCelebRes) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{1}
}

func (x *IsCelebRes) GetIsCeleb() bool {
	if x != nil {
		return x.IsCeleb
	}
	return false
}

type GetFollowersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersReq) Reset() {
	*x = GetFollowersReq{}
	mi := &file_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersReq) ProtoMessage() {}

func (x *GetFollowersReq) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersReq.ProtoReflect.Descriptor instead.
func (*GetFollowersReq) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowersReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetFollowersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerID    []string               `protobuf:"bytes,1,rep,name=FollowerID,proto3" json:"FollowerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRes) Reset() {
	*x = GetFollowersRes{}
	mi := &file_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRes) ProtoMessage() {}

func (x *GetFollowersRes) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRes.ProtoReflect.Descriptor instead.
func (*GetFollowersRes) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowersRes) GetFollowerID() []string {
	if x != nil {
		return x.FollowerID
	}
	return nil
}

var File_follow_proto protoreflect.FileDescriptor

const file_follow_proto_rawDesc = "" +
	"\n" +
	"\ffollow.proto\"$\n" +
	"\n" +
	"IsCelebReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"&\n" +
	"\n" +
	"IsCelebRes\x12\x18\n" +
	"\aIsCeleb\x18\x01 \x01(\bR\aIsCeleb\")\n" +
	"\x0fGetFollowersReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"1\n" +
	"\x0fGetFollowersRes\x12\x1e\n" +
	"\n" +
	"FollowerID\x18\x01 \x03(\tR\n" +
	"FollowerID2\x98\x01\n" +
	"\rFollowService\x122\n" +
	"\fGetFollowers\x12\x10.GetFollowersReq\x1a\x10.GetFollowersRes\x12.\n" +
	"\bGetCeleb\x12\x10.GetFollowersReq\x1a\x10.GetFollowersRes\x12#\n" +
	"\aIsCeleb\x12\v.IsCelebReq\x1a\v.IsCelebResB\x19Z\x17../services_bindings_gob\x06proto3"

var (
	file_follow_proto_rawDescOnce sync.Once
	file_follow_proto_rawDescData []byte
)

func file_follow_proto_rawDescGZIP() []byte {
	file_follow_proto_rawDescOnce.Do(func() {
		file_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)))
	})
	return file_follow_proto_rawDescData
}

var file_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_follow_proto_goTypes = []any{
	(*IsCelebReq)(nil),      // 0: IsCelebReq
	(*IsCelebRes)(nil),      // 1: IsCelebRes
	(*GetFollowersReq)(nil), // 2: GetFollowersReq
	(*GetFollowersRes)(nil), // 3: GetFollowersRes
}
var file_follow_proto_depIdxs = []int32{
	2, // 0: FollowService.GetFollowers:input_type -> GetFollowersReq
	2, // 1: FollowService.GetCeleb:input_type -> GetFollowersReq
	0, // 2: FollowService.IsCeleb:input_type -> IsCelebReq
	3, // 3: FollowService.GetFollowers:output_type -> GetFollowersRes
	3, // 4: FollowService.GetCeleb:output_type -> GetFollowersRes
	1, // 5: FollowService.IsCeleb:output_type -> IsCelebRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_follow_proto_init() }
func file_follow_proto_init() {
	if File_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follow_proto_goTypes,
		DependencyIndexes: file_follow_proto_depIdxs,
		MessageInfos:      file_follow_proto_msgTypes,
	}.Build()
	File_follow_proto = out.File
	file_follow_proto_goTypes = nil
	file_follow_proto_depIdxs = nil
}
