apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dmb-namespace.yaml
  - api_gateway/
  - user_service/
  - post_service/
  - feed_service/
  - follow_service/
  - external_secrets/
